# Generated by Django 4.1.7 on 2023-04-01 17:20

from django.db import migrations, models
import django.db.models.deletion
import todolist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=todolist.models.Time_period)),
                ('Task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.task_list')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
